### ISSUE TITLE
response 401

### ISSUE THREAD

**Issue by Peelz** [snow-actions/line-notify#7]
I just using config from exam.yml, but response 
`
{"status":401,"message":"Missing Bearer"}
`
My token is generate from personal token type.

**Comment by SnowCait** [comment]
Me too on the [example.yml](https://github.com/snow-actions/line-notify/blob/master/.github/workflows/example.yml).

**Comment by SnowCait** [comment]
@Peelz 
I regenerate access token, then I get a message. (#8)
My old access token seems to be expired.
Try 
```
curl -H 'Authorization: Bearer YOUR_ACCESS_TOKEN' https://notify-api.line.me/api/status
```

**Comment by Peelz** [comment]
Result

![Screen Shot 2563-11-24 at 20 37 33](https://user-images.githubusercontent.com/10369836/100101487-e364be80-2e94-11eb-9106-94a4271f78bb.png)

**Comment by Peelz** [comment]
I've test by using Python script it working.

**Comment by SnowCait** [comment]
Hmm..

**Comment by Peelz** [comment]
Oh, sorry my bad.
I confused to use Organization secret with private repo.
